language: c

addons:
  apt:
    packages:
    - libc6-i386
    - lib32ncurses5

dist: trusty
sudo: false

cache:
    directories:
        - gcc-arm-none-eabi-5_4-2016q3

before_script:
    - make toolchain
    - export BINPATH=$PWD/gcc-arm-none-eabi-5_4-2016q3/bin

script:
    - cd example/stm32f1
    - make
